sudo:
  false

language:
  node_js

node_js:
  - 10
  - 12

script:
  - npm run test

after_script:
  - npm run coveralls

jobs:
  include:
    - stage: release
      if: tag IS present
      node_js: 12
      deploy:
        provider: npm
        email: eskarev@gmail.com
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: j8ggiFX1YzBmyjKqPbZYnyzEghtgK4I2LE8+UiJrq4RCIKkLD6O7L/Z/6n9dUMHd6nPiO7TgxqYzVSXlk88zPgKULoQuyjgsLq9A+TX7uBv+FUmBNuaTLvHOC7ty454jDCeihoODjkEYfN8qJbVIKiDkerW1cLnXwH/MoHFEG87Dils6926VwCosBkvLc5K0iOVI8nXdN7dcOn27YBFmKTRaj6Eecd2VacEk2nvY+68JUxxC8+IBZELe6KGuE8XjVtPV8lH65el1eG6c6ymjrfTdjbaPEGQXxndoaeXn9wmc55bwoMsgKlOVJ0r7JbeGibxR9pB8RovOJUiJ0HRQn9rSdQ00KfBVovL78Rx83AANttgzb0+MidQxoCsPWniHgyldLX03bvi9nhk7DVM5V9gYNeEdt0kl42/JFtt4l7GH2IPPr4fyiFhCeT8lR6VavZ+IlbA1V4OR2lshXT9lIoe1ogJ2SdCNqZBO/NHqBI9Hjaz+RGWBcy6N2U84TXNCwBVLsR0ADneDeAaqLU5hOhPpEDu+bETyaGAReOMCe/wCU2sDnAXmq5O04LB4wVuXRO24np9XdgItAdotAKvNHQtxYIVAC/iRIw18lVSs2dAdYRk0PMARpqb/z4TT+/31ybvO7ddJKy5UHURgOpX2ybyxWgKygtdeAHVG2gerPlk=
