sudo:
  false

language:
  node_js

node_js:
  - 10
  - 12

script:
  - npm run test

after_script:
  - npm run coveralls

jobs:
  include:
    - stage: release
      if: tag IS present
      node_js: 12
      deploy:
        edge: true
        provider: npm
        email: eskarev@gmail.com
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: Qrn2o/ZeSKQQEkQHCVzzyTBmsNvaznrKmHLT+g+6cFvXAM7QfOqQ4GScQpgAzuYyb8sX49b1GiM+KIyeY4VQczRSytXe3y10lRGoAH9C/p4e3mLj+Mekoz3l7tJhubPa2PcU1I9xKtfWA+eB59g1/JonYBtBTfKe+c30tgvaaJWZzNUu0vO5riKULyWuDYS0vUeVg7gD46OOTdk6oF11oRqLVFEDDj+MsKQmO6mC0Vitte7aZva/kqChSIVZwAe/GWGkdCDDETRoq6y1cHchVOm8s0b8GWGof56M7AIhNe/16J3u+IDFr1Wcn0wJbHIOs997ms5vSV3q+9bO8DCOhH0bGaXelCsTcJLC9wt+/jtoCnPAFQTdXOpkozzmWm/q48UoJMj1T9nXJPBgJND7SWWeyx6Q2jdLyauSOD1ncqS0OZjB/fYjdVd+jSyiLOpOJjYesievO+Qrvqr0taQtgli+qn8MNJPmxgfRckymubNrhrsVJHfrjMTs8/DsMfC3/qrplmyb9sA4ko5KBLKU+XEDzlq6TjPuFndGIRo/DeAx6mP00Br+YK1vL8omAn4KeaPnQrDOH/9OgnGD622OzTyZGcqP3FvYiJagXz0t7bKtgUZ7dTaThTLFeh/Qa7EfcVA5NE3VI9iCe9/xqYpxWooRm6Wm4ueo+0YvzMypJi8=
