sudo:
  false

language:
  node_js

node_js:
  - 10
  - 12

script:
  - npm run test

after_script:
  - npm run coveralls

jobs:
  include:
    - stage: release
      if: tag IS present
      node_js: 12
      deploy:
        provider: npm
        email: eskarev@gmail.com
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: tS1Ps/m0fee386FupugxEsth5gW19WjHomXwThmvJUytpavGhLNRKjiu8cp60HQfxksJa1Ykvkr2SSWnfS3ez5ctvmcbs71Yg9KbVUIVPyn90KR+GmMDVqzf1Hm5PuNq3uzr2rYK+fhNMbzjWXN/kQCo8pfZFATfiLe1gIBTT1Bw1Da66TxuV7FVlKZgHEQ09yprbEovgd44rgwkyoUxoAY35rxLjy+U7f9Vo6dUt8FT9SlYYAxoFXI5q/jFjf7LSUIgnjchfo04DNUvxtAoqrsBq6WpHqnsgHG+B0XtUmV5YMYb3TNlQ8SHHEjeVeAXINuTAkPlbckxOKXanGj5FlHPlNlILrAXJ5DYcqRGT7eCsI9/LW5l3bMAhO61zB9w98DFB8KX95YJfSBm5jMS6HhJNozQcqv9HUOOk3ZXRTvefx3V0WNtRq21ubNMLm8p7aZu8dErDH0nGcR3MuyU/Do9nPrqTk7J9FGMcOBl/Zb6lGUy+zVPvH4YGjK/Ue4zfbBJhAsRSUwat5ps0ShWXtAORqT+gO15ksiS1caHSigJog10NGuxLBAu6CUSMGJHUhbzu7jLIW93aCYhO8bXWQkVmYn+0Lv8oYfIdmwKYb5M6G8yzDQQLzS9QzSUn74KhGZLTfpuWCrwbzDLkU5S5h3SRglZzeWrYUw33vBhCtg=
